# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish package to Nuget

on:
  push:
    branches: [ "master" ]

permissions: read-all

jobs:
  
  Build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: build
        run: dotnet build
  
  Test:

    runs-on: ubuntu-latest
    needs: 
      - Build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Test
        run: dotnet test src/tests/ResultWrapper.Test/ResultWrapper.Test.csproj
  
  Package:

    runs-on: ubuntu-latest
    needs: 
      - Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Pack
        run: dotnet pack src/ResultWrapper.Library/ResultWrapper.Library.csproj -c Release
      - name: Publish to Nuget Repo
        run: dotnet nuget push src/ResultWrapper.Library/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

